version: "0.2"
files:
  - "**/*"
ignorePaths:
  - pnpm-lock.yaml
  - .git/
  - dist/
  - .gitignore
  - .dockerignore
useGitignore: true
language: en, en-GB
allowCompoundWords: true
enableGlobDot: true
words:  
  - CPATH
  - Cppcheck
  - DCATCH
  - DCMAKE
  - DDEFAULT
  - DDISABLE
  - DFEATURE
  - DontAlign
  - Eigen
  - FLTK
  - GTKMM
  - Hostx
  - IMGUI
  - IWYU
  - Lartians
  - NOSTDLIB
  - Opencppcoverage
  - PTRACE
  - SFML
  - SYSREQUIRES
  - TLDR
  - TOLOWER
  - TOUPPER
  - VSINSTALLDIR
  - WMAIN
  - Wpedantic
  - aminya
  - asan
  - ccache
  - ccmake
  - choco
  - clangd
  - clpath
  - cmake
  - cmakelint
  - cmds
  - cobertura
  - codecov
  - codeql
  - covertura
  - cpack
  - cpmaddpackage
  - cppcoreguidelines
  - cpprc
  - cpptools
  - ctest
  - dearmor
  - eamodio
  - ehthumbs
  - fuzzer
  - gcov
  - gcovr
  - gedit
  - gtest
  - hwrap
  - ifeq
  - ifndef
  - inline-suppr
  - inplace
  - kwargs
  - lldb
  - mkdir
  - msvc
  - myproject
  - nostdlib
  - nothrow
  - nproc
  - pargs
  - pnpm
  - pwsh
  - pylance
  - refreshenv
  - rmrf
  - rtti
  - socat
  - twxs
  - vcpkg
  - vcvarsall
  - vcvarsallpath
  - vswhere
  - webp
