version: '3.4'

services:
  build:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: build
  test:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: test
  test-without-sanitizer:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: test-without-sanitizer
  coverage:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: coverage
  build-debug:
    build:
      context: ..
      dockerfile: ./docker/DockerfileDebug
      target: build-debug
  test-debug:
    build:
      context: ..
      dockerfile: ./docker/DockerfileDebug
      target: test-debug
  test-debug-without-sanitizer:
    build:
      context: ..
      dockerfile: ./docker/DockerfileDebug
      target: test-debug-without-sanitizer
  build-release:
    build:
      context: ..
      dockerfile: ./docker/DockerfileRelease
      target: build-release
  test-release:
    build:
      context: ..
      dockerfile: ./docker/DockerfileRelease
      target: test-release
  test-release-without-sanitizer:
    build:
      context: ..
      dockerfile: ./docker/DockerfileRelease
      target: test-release-without-sanitizer
  lint:
    build:
      context: ..
      dockerfile: ./docker/DockerfileMisc
      target: lint
